  name: GatorGrader

  on:
    push:
      branches: [ main ]

  jobs:
    grade:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: Setup Python
        if: always()
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up grading environment
        run: |
          sudo apt-get install rename
          pip install --upgrade pip
          pip install pipenv
          pip install notebook
          pip install pillow
          pip install markovify
          pip install textwrap3
          pipenv install --dev --three
      - name: Grade image manipulation
        run: |
          cd image-manipulation/day-0
          gradle grade
          cd ..
          cd day-1
          gradle grade
          cd ../..
        if: always()
      - name: Grade text-generation
        run: |
          cd text-generation
          gradle grade
          cd ..
        if: always()
        env:   
         PIPENV_VENV_IN_PROJECT: 1
         PIPENV_IGNORE_VIRTUALENVS: 1
